-- creates the clindata database and defines the dm and ex tables

USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'clindata')
BEGIN
    CREATE DATABASE clindata;
END
GO

USE clindata;
GO

-- drop tables if they exist
IF OBJECT_ID('dbo.ex', 'U') IS NOT NULL DROP TABLE dbo.ex;
IF OBJECT_ID('dbo.dm', 'U') IS NOT NULL DROP TABLE dbo.dm;
GO

-- DM
CREATE TABLE dbo.dm (
    STUDYID VARCHAR(20)  NOT NULL,
    DOMAIN VARCHAR(2)   NOT NULL DEFAULT 'DM',
    USUBJID VARCHAR(50) PRIMARY KEY,
    SUBJID VARCHAR(20)  NOT NULL,
    RFSTDTC VARCHAR(10),
    RFENDTC VARCHAR(10),
    RFXSTDTC VARCHAR(10)  ,         
    RFXENDTC VARCHAR(10) ,
    RFICDTC  VARCHAR(10)  ,
    RFPENDTC VARCHAR(10) ,        
    DTHDTC VARCHAR(10) ,
    DTHFL CHAR(1)     ,
    SITEID VARCHAR(10)  NOT NULL,
    AGE INT,
    AGEU VARCHAR(10) DEFAULT 'YEARS',
    SEX VARCHAR(20)  ,
    RACE VARCHAR(100) ,
    ETHNIC  VARCHAR(50) ,
    ARMCD VARCHAR(10) ,
    ARM VARCHAR(50)  ,
    ACTARMCD VARCHAR(10) ,
    ACTARM  VARCHAR(50) ,
    ARMNRS VARCHAR(200),
    ACTARMUD  VARCHAR(200) ,
    COUNTRY VARCHAR(3)   NOT NULL,
);
GO

-- EX
CREATE TABLE dbo.ex (
    STUDYID VARCHAR(20) NOT NULL,
    DOMAIN VARCHAR(2) NOT NULL DEFAULT 'EX',
    USUBJID VARCHAR(50) NOT NULL,
    EXSEQ INT NOT NULL,
    EXTRT VARCHAR(100) NULL,
    EXDOSE FLOAT NULL,
    EXDOSEU VARCHAR(10) NULL,
    EXADJ VARCHAR(500) NULL,
    EXSTDTC VARCHAR(30) NULL,         
    EXENDDTC VARCHAR(30) NULL,         
    EXSTDY VARCHAR(20) NULL,

    CONSTRAINT PK_ex PRIMARY KEY (USUBJID, EXSEQ),
    CONSTRAINT FK_ex_dm FOREIGN KEY (USUBJID) REFERENCES dbo.dm(USUBJID)
);
GO

CREATE INDEX IX_dm_country  ON dbo.dm (COUNTRY);
CREATE INDEX IX_dm_arm      ON dbo.dm (ARM);
CREATE INDEX IX_ex_usubjid  ON dbo.ex (USUBJID);
CREATE INDEX IX_ex_extrt    ON dbo.ex (EXTRT);
GO
